"""initial revision

Revision ID: 890080cdc877
Revises: 
Create Date: 2025-09-24 19:08:50.007033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890080cdc877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('receiver', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'completed', name='callstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordings')
    op.drop_table('calls')
    # ### end Alembic commands ###
